// File generated by FlutterFire / LibraGuard integration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyivw8v1Wmm51_2qXCMo45AzxmLXXBEYE',
    appId: '1:326585734757:web:8ba069097cd86f5683d88c',
    messagingSenderId: '326585734757',
    projectId: 'libraguard-57def',
    authDomain: 'libraguard-57def.firebaseapp.com',
    storageBucket: 'libraguard-57def.firebasestorage.app',
    measurementId: 'G-Y4BG0WNWVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qSlhnOnxfIARe8IPum9zo5wbR3iBkhQ',
    appId: '1:326585734757:android:3d713e9eb27c478183d88c',
    messagingSenderId: '326585734757',
    projectId: 'libraguard-57def',
    storageBucket: 'libraguard-57def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyivw8v1Wmm51_2qXCMo45AzxmLXXBEYE',
    appId: '1:326585734757:web:8ba069097cd86f5683d88c',
    messagingSenderId: '326585734757',
    projectId: 'libraguard-57def',
    storageBucket: 'libraguard-57def.firebasestorage.app',
  );
}
